//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly_Commitment
    {
        public string assembly_number { get; set; }
        public int final_buffer { get; set; }
        public int assembly_days { get; set; }
        public int machining_days { get; set; }
        public Nullable<System.DateTime> bom_date { get; set; }
        public Nullable<System.DateTime> casting_date { get; set; }
        public Nullable<System.DateTime> readytoship { get; set; }
    }
}
