//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanInfo_Jobs
    {
        public int PlanId { get; set; }
        public string BaanProjectNum { get; set; }
        public int ClassId { get; set; }
        public int JobOwnerLocation { get; set; }
        public Nullable<int> RemoteLocation { get; set; }
        public string RemoteProjectNum { get; set; }
        public string RemotePM { get; set; }
        public bool EngSched { get; set; }
        public Nullable<bool> IsBuyout { get; set; }
        public Nullable<int> Def_resp_ProfileId { get; set; }
        public string ProjectType { get; set; }
        public string Creator { get; set; }
    }
}
