//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Orders
    {
        public string SO_Nr { get; set; }
        public string SO_Ln { get; set; }
        public string SO_Sq { get; set; }
        public string SO_CustomerCode { get; set; }
        public string SO_CustomerName { get; set; }
        public string SO_Project { get; set; }
        public string SO_Item { get; set; }
        public string Item_Description { get; set; }
        public string Item_PumpLine { get; set; }
        public string Item_PumpType { get; set; }
        public Nullable<System.DateTime> SO_Date { get; set; }
        public Nullable<System.DateTime> SO_Ln_PlnDlvDate { get; set; }
        public System.DateTime SO_Ln_PlnRecDate { get; set; }
        public Nullable<System.DateTime> SO_Ln_OrigExpShpDate { get; set; }
        public Nullable<System.DateTime> SO_Ln_ExpShpDate { get; set; }
        public Nullable<System.DateTime> SO_Ln_ExpRevDate { get; set; }
        public string SO_QtyOrd { get; set; }
        public string SO_QtyDlv { get; set; }
        public string SO_QtyOpen { get; set; }
        public string SO_Unit { get; set; }
        public Nullable<double> SO_Price { get; set; }
        public Nullable<double> SO_Ln_OpenAmount { get; set; }
        public string SO_Currency { get; set; }
        public string SO_CustomerPO { get; set; }
        public Nullable<System.DateTime> SO_CustomerPO_Date { get; set; }
        public string SO_PM_Name { get; set; }
        public string SO_PLS_Name { get; set; }
        public string SO_GPS_Quote { get; set; }
        public string SO_Reference_A { get; set; }
        public string SO_Reference_B { get; set; }
        public string ProdOrderNr { get; set; }
        public string ProdOrder_Status { get; set; }
        public string ProdOrder_Route { get; set; }
        public Nullable<System.DateTime> ProdOrder_PlnStrDate { get; set; }
        public Nullable<System.DateTime> ProdOrder_PlnDlvDate { get; set; }
        public Nullable<System.DateTime> ProdOrder_ConfDate { get; set; }
        public string ProdOrder_QtyOrd { get; set; }
        public string ProdOrder_QtyDlv { get; set; }
        public string ProdOrder_QtyRjc { get; set; }
        public string ProdOrder_QtyBal { get; set; }
        public string Oper_ComplTotal { get; set; }
        public string FirstInProcessOperationMachine { get; set; }
        public string FirstInProcessOperationMachineName { get; set; }
        public string FirstInProcessOperation { get; set; }
        public System.DateTime MinStartDate { get; set; }
        public System.DateTime MaxDelivDate { get; set; }
        public Nullable<bool> HasChangedPRD { get; set; }
        public string Company { get; set; }
        public string SlsOff_Code { get; set; }
        public string SlsOff_Name { get; set; }
        public string Location { get; set; }
        public string OrderType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> DaysBuffer { get; set; }
        public Nullable<System.DateTime> ProdOrder_ReqDlvDate { get; set; }
    }
}
