//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shepherd_permissions
    {
        public int id { get; set; }
        public string aliasname { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public Nullable<bool> active { get; set; }
        public string location { get; set; }
        public string baancompany { get; set; }
    }
}
