//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shepherd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long TaskId { get; set; }
        public int PlanId { get; set; }
        public int tNumber { get; set; }
        public string tName { get; set; }
        public Nullable<System.DateTime> tStart { get; set; }
        public Nullable<System.DateTime> tEnd { get; set; }
        public Nullable<System.DateTime> tStart_Actual { get; set; }
        public Nullable<System.DateTime> tEnd_Actual { get; set; }
        public Nullable<System.DateTime> tStart_Cust { get; set; }
        public Nullable<System.DateTime> tEnd_Cust { get; set; }
        public string tLink { get; set; }
        public Nullable<bool> tMilestone { get; set; }
        public string tResponsible { get; set; }
        public Nullable<int> RespId { get; set; }
        public Nullable<int> tCompletion { get; set; }
        public Nullable<bool> tGroup { get; set; }
        public Nullable<int> tParent { get; set; }
        public Nullable<bool> tOpen { get; set; }
        public string tDependency { get; set; }
        public string tCaption { get; set; }
        public Nullable<int> TrackerId { get; set; }
        public Nullable<int> AlertId { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public Nullable<bool> Publish { get; set; }
        public string Scheduling { get; set; }
        public Nullable<bool> DurationDriven { get; set; }
        public Nullable<int> BLineId { get; set; }
        public string CatId { get; set; }
        public Nullable<int> LinkId { get; set; }
        public Nullable<long> P_NoteId { get; set; }
        public Nullable<bool> showReport { get; set; }
        public Nullable<bool> integrate { get; set; }
        public Nullable<System.DateTime> tStart_back { get; set; }
        public Nullable<System.DateTime> tEnd_back { get; set; }
    }
}
